// /content — Content creation & scheduling commands
const { Markup } = require('telegraf');
const db = require('../../server/config/database');

module.exports = function (bot) {
  bot.command('content', (ctx) => {
    const text = ctx.message.text.trim();
    const args = text.split(/\s+/).slice(1);
    const subcommand = (args[0] || 'list').toLowerCase();

    switch (subcommand) {
      case 'create':
        return contentCreate(ctx, args.slice(1).join(' '));
      case 'list':
        return contentList(ctx);
      case 'schedule':
        return contentSchedule(ctx, args[1], args.slice(2).join(' '));
      case 'publish':
        return contentPublish(ctx, args[1]);
      default:
        return ctx.replyWithHTML(
          '📝 <b>Content Commands</b>\n\n' +
          '<code>/content create &lt;topic&gt;</code> — Create draft\n' +
          '<code>/content list</code> — Drafts & scheduled\n' +
          '<code>/content schedule &lt;id&gt; &lt;datetime&gt;</code> — Schedule\n' +
          '<code>/content publish &lt;id&gt;</code> — Publish now'
        );
    }
  });

  bot.hears('📝 Content Ideas', (ctx) => {
    return contentList(ctx);
  });

  bot.action('action_add_content', (ctx) => {
    ctx.answerCbQuery();
    ctx.session = ctx.session || {};
    ctx.session.wizard = { active: true, type: 'create_content', step: 'topic', data: {} };
    return ctx.replyWithHTML('📝 <b>Create Content Draft</b>\n\nWhat is the topic or title of the post? (Type /cancel to abort)');
  });

  // ── Create content draft ──
  async function contentCreate(ctx, topic) {
    if (!topic) {
      return ctx.replyWithHTML('Usage: <code>/content create &lt;topic&gt;</code>');
    }

    try {
      // Create a draft — in the future the AI agent will generate the body
      const draftBody = `[AI Draft Pending]\n\nTopic: ${topic}\n\nThis content will be generated by the AI Content Creator agent. Use /agent ask to generate content.`;

      const result = db.prepare(
        'INSERT INTO content (title, body, type, platform, status, created_by) VALUES (?, ?, ?, ?, ?, ?)'
      ).run(topic, draftBody, 'post', 'facebook', 'draft', 'telegram');

      const keyboard = Markup.inlineKeyboard([
        [
          Markup.button.callback('📋 View Drafts', 'content_list_all'),
          Markup.button.callback('📅 Schedule', `content_sched_prompt_${result.lastInsertRowid}`),
        ],
        [
          Markup.button.callback('🚀 Publish Now', `content_pub_${result.lastInsertRowid}`),
        ],
      ]);

      return ctx.replyWithHTML(
        `✅ <b>Content Draft Created!</b>\n\n` +
        `📝 Title: <b>${topic}</b>\n` +
        `📌 Status: draft\n` +
        `📱 Platform: facebook\n` +
        `🆔 ID: #${result.lastInsertRowid}\n\n` +
        `<i>The AI Content Creator will generate the full post body. For now, a placeholder draft has been saved.</i>`,
        keyboard
      );
    } catch (err) {
      console.error('Content create error:', err.message);
      return ctx.replyWithHTML('⚠️ Failed to create content draft.');
    }
  }

  // ── List content ──
  async function contentList(ctx) {
    try {
      const items = db.prepare(
        'SELECT id, title, status, platform, scheduled_at, created_at FROM content ORDER BY created_at DESC LIMIT 15'
      ).all();

      if (items.length === 0) {
        const keyboard = Markup.inlineKeyboard([
          [
            Markup.button.callback('➕ Create Draft', 'action_add_content'),
            Markup.button.callback('🔄 Refresh', 'content_list_all')
          ]
        ]);
        return ctx.replyWithHTML(
          '📝 <b>Content</b>\n\nNo content yet! Create your first draft:',
          keyboard
        );
      }

      const statusEmoji = {
        draft: '📝', scheduled: '📅', published: '✅', failed: '❌',
      };

      let msg = '📝 <b>Content Library</b>\n━━━━━━━━━━━━━━━━━━━\n\n';
      items.forEach((c) => {
        const emoji = statusEmoji[c.status] || '📄';
        const sched = c.scheduled_at ? ` — 📅 ${c.scheduled_at}` : '';
        msg += `${emoji} <b>#${c.id}</b> ${c.title}\n`;
        msg += `   ${c.status} · ${c.platform}${sched}\n\n`;
      });

      const buttons = items.slice(0, 5).map((c) => [
        Markup.button.callback(`👁 #${c.id} ${c.title.substring(0, 20)}`, `content_view_${c.id}`),
      ]);

      buttons.push([
        Markup.button.callback('➕ Create Draft', 'action_add_content'),
        Markup.button.callback('🔄 Refresh Library', 'content_list_all')
      ]);

      return ctx.replyWithHTML(msg, Markup.inlineKeyboard(buttons));
    } catch (err) {
      console.error('Content list error:', err.message);
      return ctx.replyWithHTML('⚠️ Failed to load content.');
    }
  }

  // ── Schedule content ──
  async function contentSchedule(ctx, id, datetime) {
    if (!id || !datetime) {
      return ctx.replyWithHTML(
        'Usage: <code>/content schedule &lt;id&gt; &lt;datetime&gt;</code>\n' +
        'Example: <code>/content schedule 1 2026-05-23 10:00</code>'
      );
    }

    try {
      const content = db.prepare('SELECT * FROM content WHERE id = ?').get(id);
      if (!content) return ctx.replyWithHTML(`❌ Content #${id} not found.`);

      db.prepare(
        'UPDATE content SET status = ?, scheduled_at = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?'
      ).run('scheduled', datetime, id);

      return ctx.replyWithHTML(
        `📅 <b>Content Scheduled!</b>\n\n` +
        `📝 <b>${content.title}</b>\n` +
        `📅 Scheduled for: <b>${datetime}</b>\n` +
        `📱 Platform: ${content.platform}`
      );
    } catch (err) {
      console.error('Content schedule error:', err.message);
      return ctx.replyWithHTML('⚠️ Failed to schedule content.');
    }
  }

  // ── Publish content (placeholder) ──
  async function contentPublish(ctx, id) {
    if (!id) {
      return ctx.replyWithHTML('Usage: <code>/content publish &lt;id&gt;</code>');
    }

    try {
      const content = db.prepare('SELECT * FROM content WHERE id = ?').get(id);
      if (!content) return ctx.replyWithHTML(`❌ Content #${id} not found.`);

      db.prepare(
        'UPDATE content SET status = ?, published_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = ?'
      ).run('published', id);

      return ctx.replyWithHTML(
        `🚀 <b>Content Published!</b>\n\n` +
        `📝 <b>${content.title}</b>\n` +
        `📱 Platform: ${content.platform}\n` +
        `📅 Published at: ${new Date().toISOString()}\n\n` +
        `<i>Note: Facebook API integration will post automatically when configured.</i>`
      );
    } catch (err) {
      console.error('Content publish error:', err.message);
      return ctx.replyWithHTML('⚠️ Failed to publish content.');
    }
  }

  // ── Callback: View content detail ──
  bot.action(/^content_view_(\d+)$/, (ctx) => {
    const id = ctx.match[1];
    ctx.answerCbQuery();
    try {
      const content = db.prepare('SELECT * FROM content WHERE id = ?').get(id);
      if (!content) return ctx.replyWithHTML('❌ Content not found.');

      const body = content.body
        ? content.body.substring(0, 500) + (content.body.length > 500 ? '…' : '')
        : 'No body';

      const msg = [
        `📝 <b>Content #${content.id}</b>`,
        `━━━━━━━━━━━━━━━━━━━`,
        `📌 <b>Title:</b> ${content.title}`,
        `📱 <b>Platform:</b> ${content.platform}`,
        `📊 <b>Status:</b> ${content.status}`,
        `📅 <b>Scheduled:</b> ${content.scheduled_at || '—'}`,
        `📅 <b>Published:</b> ${content.published_at || '—'}`,
        ``,
        `<b>Body:</b>`,
        `<code>${body}</code>`,
      ].join('\n');

      const keyboard = Markup.inlineKeyboard([
        [
          Markup.button.callback('🚀 Publish', `content_pub_${content.id}`),
          Markup.button.callback('🗑 Delete', `content_del_${content.id}`),
        ],
      ]);

      return ctx.replyWithHTML(msg, keyboard);
    } catch (err) {
      return ctx.replyWithHTML('⚠️ Failed to load content.');
    }
  });

  // ── Callback: Publish from button ──
  bot.action(/^content_pub_(\d+)$/, (ctx) => {
    const id = ctx.match[1];
    ctx.answerCbQuery('Publishing…');
    try {
      const content = db.prepare('SELECT * FROM content WHERE id = ?').get(id);
      if (!content) return ctx.replyWithHTML('❌ Content not found.');

      db.prepare(
        'UPDATE content SET status = ?, published_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = ?'
      ).run('published', id);

      return ctx.replyWithHTML(`🚀 Content "<b>${content.title}</b>" marked as published.`);
    } catch (err) {
      return ctx.replyWithHTML('⚠️ Failed to publish.');
    }
  });

  // ── Callback: Delete content ──
  bot.action(/^content_del_(\d+)$/, (ctx) => {
    const id = ctx.match[1];
    ctx.answerCbQuery();
    try {
      db.prepare('DELETE FROM content WHERE id = ?').run(id);
      return ctx.replyWithHTML(`🗑 Content #${id} deleted.`);
    } catch (err) {
      return ctx.replyWithHTML('⚠️ Failed to delete.');
    }
  });

  // ── Callback: List all ──
  bot.action('content_list_all', (ctx) => {
    ctx.answerCbQuery();
    return contentList(ctx);
  });

  // ── Callback: Schedule prompt ──
  bot.action(/^content_sched_prompt_(\d+)$/, (ctx) => {
    const id = ctx.match[1];
    ctx.answerCbQuery();
    return ctx.replyWithHTML(
      `📅 To schedule content #${id}, send:\n<code>/content schedule ${id} 2026-05-23 10:00</code>`
    );
  });
};
